# usage: conda env create
name: viz_3d
channels:
  - conda-forge
dependencies:
  - attrs=21.4.0
  - libblas=3.9.0
  - liblapack=3.9.0
  - libopenblas=0.3.20
  - libcblas=3.9.0
  - certifi=2021.10.8
  - click=8.0.4
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cython=0.29.28
  - fiona=1.8.21
  - geopandas=0.10.2
  - geopandas-base=0.10.2
  - libllvm11=11.1.0
  - libzip=1.8.0
  - llvm-openmp=13.0.1
  - llvmlite=0.38.0
  - lz4=4.0.0
  - munch=2.5.0
  - numba=0.55.1
  - numpy=1.20.3
  - pandas=1.4.1
  - pcre=8.45
  - pillow=9.1.0
  - pip=22.0.4
  - psutil=5.9.0
  - psycopg2=2.9.3
  - psycopg2-binary=2.9.3
  - pthread-stubs=0.4
  - pycparser=2.21
  - pyproj=3.3.0
  - python=3.9.12
  - python-dateutil=2.8.2
  - pytz=2022.1
  - pyzmq=22.3.0
  - six=1.16.0
  - pip:
    - git+https://github.com/PermafrostDiscoveryGateway/py3dtiles.git
    - triangle==20200424
